#!/bin/bash
set -e

TARGET="${1:-.}"
SKILLS_DIR="${TARGET}/.opencode/skills"
AGENTS_FILE="${TARGET}/AGENTS.md"
INSTALLER_MARKER="# Auto-generated by agent-skills install-opencode.sh"

echo "Installing agent-skills into ${TARGET}" >&2

command -v git >/dev/null 2>&1 || { echo "ERROR: git not found on PATH" >&2; exit 1; }

# 1. Ensure target .opencode/ exists.
mkdir -p "$(dirname "${SKILLS_DIR}")"

# 2. Symlink .opencode/skills -> this repo's skills/.
REPO_SKILLS="$(cd "$(dirname "$0")/.." && pwd)/skills"
if [ -L "${SKILLS_DIR}" ] && [ "$(readlink -f "${SKILLS_DIR}")" = "${REPO_SKILLS}" ]; then
  echo "  ✓ ${SKILLS_DIR} already linked" >&2
else
  ln -sfn "${REPO_SKILLS}" "${SKILLS_DIR}"
  echo "  ✓ linked ${SKILLS_DIR} -> ${REPO_SKILLS}" >&2
fi

# 3. Scaffold AGENTS.md if absent. Never overwrite an existing file.
if [ ! -f "${AGENTS_FILE}" ]; then
  {
    echo "${INSTALLER_MARKER}"
    echo "# AGENTS.md"
    echo ""
    echo "This project uses agent-skills. Skills live in \`.opencode/skills/\` (symlinked)."
    echo ""
    echo "## OpenCode Integration"
    echo ""
    echo "- If a task matches a skill, invoke it via the \`skill\` tool."
    echo "- Prefer \`AGENTS.md\` over \`CLAUDE.md\` when both exist."
    echo ""
    echo "See https://github.com/dbc-tech/agent-skills for the full catalog."
  } >"${AGENTS_FILE}"
  echo "  ✓ wrote ${AGENTS_FILE}" >&2
else
  echo "  ✓ ${AGENTS_FILE} already present (left untouched)" >&2
fi

# 4. Verify.
[ -d "${REPO_SKILLS}" ] || { echo "ERROR: skills/ not found at ${REPO_SKILLS}" >&2; exit 1; }
[ -L "${SKILLS_DIR}" ]  || { echo "ERROR: ${SKILLS_DIR} not a symlink" >&2; exit 1; }

echo "Done. Skills available at ${SKILLS_DIR}"
