#!/bin/bash
# install-opencode-test.sh - Tests for scripts/install-opencode.sh
#
# Asserts:
#   (a) running the installer in a fresh /tmp dir creates the symlink and a marker-tagged AGENTS.md
#   (b) re-running it is a no-op (idempotent)
#   (c) running it when git is not on PATH exits non-zero with an error message
#   (d) running it against a target with a pre-existing hand-edited AGENTS.md leaves that file untouched

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
INSTALLER="${SCRIPT_DIR}/install-opencode.sh"
INSTALLER_MARKER="# Auto-generated by agent-skills install-opencode.sh"

# --- Setup: create a temp dir ---
TMPDIR="$(mktemp -d)"
trap 'rm -rf "${TMPDIR}"' EXIT

echo "Testing install-opencode.sh in ${TMPDIR}" >&2

# --- (a) Fresh install: creates symlink + marker-tagged AGENTS.md ---
echo "  • (a) Fresh install..." >&2
bash "${INSTALLER}" "${TMPDIR}" >/dev/null 2>&1

# Verify symlink
if [ ! -L "${TMPDIR}/.opencode/skills" ]; then
  echo "FAIL: .opencode/skills symlink not created" >&2
  exit 1
fi

# Verify symlink points to this repo's skills/
REPO_SKILLS="$(cd "${SCRIPT_DIR}/.." && pwd)/skills"
if [ "$(readlink -f "${TMPDIR}/.opencode/skills")" != "${REPO_SKILLS}" ]; then
  echo "FAIL: symlink points to $(readlink -f "${TMPDIR}/.opencode/skills"), expected ${REPO_SKILLS}" >&2
  exit 1
fi

# Verify AGENTS.md was created with marker on line 1
if [ ! -f "${TMPDIR}/AGENTS.md" ]; then
  echo "FAIL: AGENTS.md not created" >&2
  exit 1
fi

if ! head -n1 "${TMPDIR}/AGENTS.md" | grep -qF "${INSTALLER_MARKER}"; then
  echo "FAIL: AGENTS.md missing installer marker on line 1" >&2
  exit 1
fi

echo "  ✓ (a) Fresh install OK" >&2

# --- (b) Re-run is idempotent ---
echo "  • (b) Idempotent re-run..." >&2

# Capture state before re-run
BEFORE_SYMLINK="$(readlink "${TMPDIR}/.opencode/skills")"
BEFORE_AGENTS_MD5="$(md5sum "${TMPDIR}/AGENTS.md" | cut -d' ' -f1)"

bash "${INSTALLER}" "${TMPDIR}" >/dev/null 2>&1

AFTER_SYMLINK="$(readlink "${TMPDIR}/.opencode/skills")"
AFTER_AGENTS_MD5="$(md5sum "${TMPDIR}/AGENTS.md" | cut -d' ' -f1)"

if [ "${BEFORE_SYMLINK}" != "${AFTER_SYMLINK}" ]; then
  echo "FAIL: symlink changed on re-run (was: ${BEFORE_SYMLINK}, now: ${AFTER_SYMLINK})" >&2
  exit 1
fi

if [ "${BEFORE_AGENTS_MD5}" != "${AFTER_AGENTS_MD5}" ]; then
  echo "FAIL: AGENTS.md changed on re-run" >&2
  exit 1
fi

echo "  ✓ (b) Idempotent re-run OK" >&2

# --- (c) git not on PATH exits non-zero ---
echo "  • (c) git not on PATH..." >&2

# Create a fake git that acts as "command not found" (exit 127)
# and a minimal PATH containing only the fake bin (no real git)
# plus the essentials the installer needs: bash builtins handle
# mkdir/echo/test internally, but ln and readlink need /usr/bin.
# We put a fake git in our fake bin and set PATH so the fake is
# found first; the real git at /usr/bin and /bin is excluded by
# not including those dirs (the installer's commands that need
# external tools will still work because set -e + the git check
# fires before any external command is called).
FAKE_BIN="$(mktemp -d)"
trap 'rm -rf "${TMPDIR}" "${FAKE_BIN}"' EXIT
printf '#!/bin/bash\nexit 127\n' > "${FAKE_BIN}/git"
chmod +x "${FAKE_BIN}/git"

# Use env -i to start with a clean environment, then set only
# PATH to our fake bin (no real git discoverable).
if env -i PATH="${FAKE_BIN}" bash "${INSTALLER}" "${TMPDIR}/subdir2" >/dev/null 2>&1; then
  echo "FAIL: installer succeeded without git on PATH (should have exited non-zero)" >&2
  exit 1
fi

echo "  ✓ (c) git not on PATH exits non-zero OK" >&2

# --- (d) Pre-existing hand-edited AGENTS.md is left untouched ---
echo "  • (d) Hand-edited AGENTS.md untouched..." >&2

TMPDIR2="$(mktemp -d)"

# Create a hand-edited AGENTS.md (no marker on line 1)
echo "# My custom project rules" > "${TMPDIR2}/AGENTS.md"
echo "Do not touch this file." >> "${TMPDIR2}/AGENTS.md"

BEFORE_MD5="$(md5sum "${TMPDIR2}/AGENTS.md" | cut -d' ' -f1)"

bash "${INSTALLER}" "${TMPDIR2}" >/dev/null 2>&1

AFTER_MD5="$(md5sum "${TMPDIR2}/AGENTS.md" | cut -d' ' -f1)"

if [ "${BEFORE_MD5}" != "${AFTER_MD5}" ]; then
  echo "FAIL: hand-edited AGENTS.md was modified (md5 changed from ${BEFORE_MD5} to ${AFTER_MD5})" >&2
  exit 1
fi

# Clean up TMPDIR2
rm -rf "${TMPDIR2}"

echo "  ✓ (d) Hand-edited AGENTS.md untouched OK" >&2

echo "install-opencode OK"
