#!/bin/bash
set -e

TARGET="${1:-.}"
SKILLS_DIR="${TARGET}/.opencode/skills"
AGENTS_FILE="${TARGET}/AGENTS.md"
INSTALLER_MARKER="# Auto-generated by agent-skills install-opencode.sh"

echo "Updating agent-skills in ${TARGET}" >&2

# 1. Pull latest skills from the repo this script lives in.
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
echo "  • pulling latest in ${REPO_ROOT}" >&2
git -C "${REPO_ROOT}" pull --ff-only

# 2. Re-verify the symlink. Recreate if missing.
REPO_SKILLS="${REPO_ROOT}/skills"
if [ ! -L "${SKILLS_DIR}" ] || [ "$(readlink -f "${SKILLS_DIR}")" != "${REPO_SKILLS}" ]; then
  mkdir -p "$(dirname "${SKILLS_DIR}")"
  ln -sfn "${REPO_SKILLS}" "${SKILLS_DIR}"
  echo "  ✓ re-linked ${SKILLS_DIR} -> ${REPO_SKILLS}" >&2
else
  echo "  ✓ ${SKILLS_DIR} already linked" >&2
fi

# 3. Re-sync commands into the global OpenCode config directory.
#    Mirrors install-opencode.sh: OPENCODE_CONFIG_DIR > XDG_CONFIG_HOME > ~/.config.
REPO_COMMANDS="${REPO_ROOT}/.claude/commands"
if [ -n "${OPENCODE_CONFIG_DIR}" ]; then
  OPENCODE_CONFIG="${OPENCODE_CONFIG_DIR}"
elif [ -n "${XDG_CONFIG_HOME}" ]; then
  OPENCODE_CONFIG="${XDG_CONFIG_HOME}/opencode"
else
  OPENCODE_CONFIG="${HOME}/.config/opencode"
fi
COMMANDS_TARGET="${OPENCODE_CONFIG}/commands"

if [ -d "${REPO_COMMANDS}" ]; then
  mkdir -p "${COMMANDS_TARGET}"
  for cmd_file in "${REPO_COMMANDS}"/*.md; do
    [ -f "$cmd_file" ] || continue
    cmd_name="$(basename "$cmd_file")"
    cmd_target="${COMMANDS_TARGET}/${cmd_name}"
    if [ -L "${cmd_target}" ] && [ "$(readlink -f "${cmd_target}")" = "${cmd_file}" ]; then
      echo "  ✓ ${cmd_target} already linked" >&2
    else
      ln -sfn "${cmd_file}" "${cmd_target}"
      echo "  ✓ linked ${cmd_target} -> ${cmd_file}" >&2
    fi
  done
else
  echo "  ⚠ no .claude/commands/ found in repo, skipping command sync" >&2
fi

# 4. Refresh AGENTS.md only if it carries the installer marker.
if [ -f "${AGENTS_FILE}" ] && head -n1 "${AGENTS_FILE}" | grep -qF "${INSTALLER_MARKER}"; then
  # Re-scaffold with the latest template (marker preserved).
  {
    echo "${INSTALLER_MARKER}"
    echo "# AGENTS.md"
    echo ""
    echo "This project uses agent-skills. Skills live in \`.opencode/skills/\` (symlinked)."
    echo ""
    echo "## OpenCode Integration"
    echo ""
    echo "- If a task matches a skill, invoke it via the \`skill\` tool."
    echo "- Prefer \`AGENTS.md\` over \`CLAUDE.md\` when both exist."
    echo ""
    echo "See https://github.com/dbc-tech/agent-skills for the full catalog."
  } >"${AGENTS_FILE}"
  echo "  ✓ refreshed ${AGENTS_FILE} (installer-managed)" >&2
elif [ -f "${AGENTS_FILE}" ]; then
  echo "  ✓ ${AGENTS_FILE} is hand-edited (left untouched)" >&2
else
  echo "  • ${AGENTS_FILE} absent; run install-opencode.sh first" >&2
  exit 1
fi

# 5. Verify.
[ -L "${SKILLS_DIR}" ] || { echo "ERROR: ${SKILLS_DIR} not a symlink after update" >&2; exit 1; }

echo "Done. Skills at ${SKILLS_DIR}, commands at ${COMMANDS_TARGET}"
