#!/bin/bash
set -e

TARGET="${1:-.}"
SKILLS_DIR="${TARGET}/.opencode/skills"
AGENTS_FILE="${TARGET}/AGENTS.md"
INSTALLER_MARKER="# Auto-generated by agent-skills install-opencode.sh"

echo "Updating agent-skills in ${TARGET}" >&2

# 1. Pull latest skills from the repo this script lives in.
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
echo "  • pulling latest in ${REPO_ROOT}" >&2
git -C "${REPO_ROOT}" pull --ff-only

# 2. Re-verify the symlink. Recreate if missing.
REPO_SKILLS="${REPO_ROOT}/skills"
if [ ! -L "${SKILLS_DIR}" ] || [ "$(readlink -f "${SKILLS_DIR}")" != "${REPO_SKILLS}" ]; then
  mkdir -p "$(dirname "${SKILLS_DIR}")"
  ln -sfn "${REPO_SKILLS}" "${SKILLS_DIR}"
  echo "  ✓ re-linked ${SKILLS_DIR} -> ${REPO_SKILLS}" >&2
else
  echo "  ✓ ${SKILLS_DIR} already linked" >&2
fi

# 3. Refresh AGENTS.md only if it carries the installer marker.
if [ -f "${AGENTS_FILE}" ] && head -n1 "${AGENTS_FILE}" | grep -qF "${INSTALLER_MARKER}"; then
  # Re-scaffold with the latest template (marker preserved).
  {
    echo "${INSTALLER_MARKER}"
    echo "# AGENTS.md"
    echo ""
    echo "This project uses agent-skills. Skills live in \`.opencode/skills/\` (symlinked)."
    echo ""
    echo "## OpenCode Integration"
    echo ""
    echo "- If a task matches a skill, invoke it via the \`skill\` tool."
    echo "- Prefer \`AGENTS.md\` over \`CLAUDE.md\` when both exist."
    echo ""
    echo "See https://github.com/addyosmani/agent-skills for the full catalog."
  } >"${AGENTS_FILE}"
  echo "  ✓ refreshed ${AGENTS_FILE} (installer-managed)" >&2
elif [ -f "${AGENTS_FILE}" ]; then
  echo "  ✓ ${AGENTS_FILE} is hand-edited (left untouched)" >&2
else
  echo "  • ${AGENTS_FILE} absent; run install-opencode.sh first" >&2
  exit 1
fi

# 4. Verify.
[ -L "${SKILLS_DIR}" ] || { echo "ERROR: ${SKILLS_DIR} not a symlink after update" >&2; exit 1; }

echo "Done. Skills at ${SKILLS_DIR}" >&2
