#!/bin/bash
# update-opencode-test.sh - Tests for scripts/update-opencode.sh
#
# Asserts:
#   (a) marker-tagged AGENTS.md is refreshed
#   (b) hand-edited AGENTS.md is left byte-for-byte unchanged
#   (c) missing AGENTS.md exits non-zero
#   (d) missing symlink is recreated
#
# Stubs `git pull` so it doesn't need network access.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
UPDATER="${SCRIPT_DIR}/update-opencode.sh"
INSTALLER="${SCRIPT_DIR}/install-opencode.sh"
INSTALLER_MARKER="# Auto-generated by agent-skills install-opencode.sh"

# --- Create a fake git that stubs `pull` and delegates everything else ---
FAKE_BIN="$(mktemp -d)"
REAL_GIT="$(command -v git)"
cat > "${FAKE_BIN}/git" <<EOF
#!/bin/bash
if [ "\$1" = "pull" ]; then
  echo "stub: git pull (no network)" >&2
  exit 0
fi
exec "${REAL_GIT}" "\$@"
EOF
chmod +x "${FAKE_BIN}/git"

# --- Setup: create a temp dir ---
TMPDIR="$(mktemp -d)"
trap 'rm -rf "${TMPDIR}" "${FAKE_BIN}"' EXIT

echo "Testing update-opencode.sh in ${TMPDIR}" >&2

# --- Pre-requisite: install first so we have a baseline ---
bash "${INSTALLER}" "${TMPDIR}" >/dev/null 2>&1

# --- (a) Marker-tagged AGENTS.md is refreshed ---
echo "  • (a) Marker-tagged AGENTS.md refreshed..." >&2

# The install already created a marker-tagged AGENTS.md. Modify the
# template slightly to simulate a version change, then run the updater
# and verify the file was refreshed to the current template.
echo "Stale content that should be replaced" >> "${TMPDIR}/AGENTS.md"

BEFORE_MD5="$(md5sum "${TMPDIR}/AGENTS.md" | cut -d' ' -f1)"

PATH="${FAKE_BIN}:${PATH}" bash "${UPDATER}" "${TMPDIR}" >/dev/null 2>&1

AFTER_MD5="$(md5sum "${TMPDIR}/AGENTS.md" | cut -d' ' -f1)"

if [ "${BEFORE_MD5}" = "${AFTER_MD5}" ]; then
  echo "FAIL: AGENTS.md was not refreshed (md5 unchanged)" >&2
  exit 1
fi

# Verify the refreshed file still has the marker on line 1
if ! head -n1 "${TMPDIR}/AGENTS.md" | grep -qF "${INSTALLER_MARKER}"; then
  echo "FAIL: refreshed AGENTS.md lost the installer marker" >&2
  exit 1
fi

# Verify the stale content was removed (file should end with the catalog link)
if tail -1 "${TMPDIR}/AGENTS.md" | grep -q "Stale content"; then
  echo "FAIL: stale content was not removed by refresh" >&2
  exit 1
fi

echo "  ✓ (a) Marker-tagged AGENTS.md refreshed OK" >&2

# --- (b) Hand-edited AGENTS.md is left byte-for-byte unchanged ---
echo "  • (b) Hand-edited AGENTS.md untouched..." >&2

TMPDIR2="$(mktemp -d)"

# Create a hand-edited AGENTS.md (no marker on line 1)
cat > "${TMPDIR2}/AGENTS.md" <<'EOF'
# My Custom Project Rules

This is a hand-edited file. Do not touch.
Some custom agent rules go here.
EOF

# Also create the symlink so the updater doesn't fail on step 2
mkdir -p "${TMPDIR2}/.opencode"
REPO_SKILLS="$(cd "${SCRIPT_DIR}/.." && pwd)/skills"
ln -sfn "${REPO_SKILLS}" "${TMPDIR2}/.opencode/skills"

BEFORE_MD5="$(md5sum "${TMPDIR2}/AGENTS.md" | cut -d' ' -f1)"

PATH="${FAKE_BIN}:${PATH}" bash "${UPDATER}" "${TMPDIR2}" >/dev/null 2>&1

AFTER_MD5="$(md5sum "${TMPDIR2}/AGENTS.md" | cut -d' ' -f1)"

if [ "${BEFORE_MD5}" != "${AFTER_MD5}" ]; then
  echo "FAIL: hand-edited AGENTS.md was modified (md5 changed)" >&2
  exit 1
fi

rm -rf "${TMPDIR2}"

echo "  ✓ (b) Hand-edited AGENTS.md untouched OK" >&2

# --- (c) Missing AGENTS.md exits non-zero ---
echo "  • (c) Missing AGENTS.md exits non-zero..." >&2

TMPDIR3="$(mktemp -d)"

# Create the symlink but no AGENTS.md
mkdir -p "${TMPDIR3}/.opencode"
ln -sfn "${REPO_SKILLS}" "${TMPDIR3}/.opencode/skills"

if PATH="${FAKE_BIN}:${PATH}" bash "${UPDATER}" "${TMPDIR3}" >/dev/null 2>&1; then
  echo "FAIL: updater succeeded with missing AGENTS.md (should exit non-zero)" >&2
  exit 1
fi

rm -rf "${TMPDIR3}"

echo "  ✓ (c) Missing AGENTS.md exits non-zero OK" >&2

# --- (d) Missing symlink is recreated ---
echo "  • (d) Missing symlink recreated..." >&2

# Remove the symlink from the first temp dir (which has a marker-tagged AGENTS.md)
rm -f "${TMPDIR}/.opencode/skills"

PATH="${FAKE_BIN}:${PATH}" bash "${UPDATER}" "${TMPDIR}" >/dev/null 2>&1

if [ ! -L "${TMPDIR}/.opencode/skills" ]; then
  echo "FAIL: symlink was not recreated" >&2
  exit 1
fi

if [ "$(readlink -f "${TMPDIR}/.opencode/skills")" != "${REPO_SKILLS}" ]; then
  echo "FAIL: symlink points to wrong location: $(readlink -f "${TMPDIR}/.opencode/skills")" >&2
  exit 1
fi

echo "  ✓ (d) Missing symlink recreated OK" >&2

echo "update-opencode OK"
